import { createKernel, createTestPlatform } from "@cora-framework/core"
import { createTestDatabase } from "@cora-framework/db"
import { describe, expect, it } from "vitest"
import config from "../template/cora.config.js"
import { buildModules } from "../template/src/server/build-modules.js"

/**
 * `packages/create-cora-server/template/**` is excluded from the root vitest
 * run (see `vitest.config.ts`'s `exclude`), since it is committed source for
 * scaffolded projects, not part of this monorepo's own test suite. That
 * means the template's own `build-modules.test.ts` never actually runs here
 * - it only runs inside a project generated by `scaffold()`.
 *
 * This test closes that gap: it reaches into the template source via a
 * relative import (proving the relative import path and workspace package
 * resolution both work, without un-excluding `template/` from vitest) and
 * boots the exact same `buildModules` the template ships, headlessly,
 * through `createKernel`. If `createCyberMpPlatform`, any module factory
 * name, or any export name the template relies on ever drifts from what the
 * workspace packages actually export, this test fails here - in the
 * monorepo's own suite - rather than only surfacing once someone scaffolds a
 * project and runs `tsc` against it.
 */
describe("template wiring (packages/create-cora-server/template)", () => {
  it("boots the template's buildModules on a headless test platform", async () => {
    const { platform } = createTestPlatform()
    const db = createTestDatabase()

    const kernel = await createKernel({
      platform,
      db,
      modules: buildModules(config),
    })

    expect(kernel.disabledModules).toEqual([])

    await kernel.shutdown()
  })
})
