export {
  defineItemCatalog,
  ITEM_CATEGORIES,
  ITEM_ID_PATTERN,
  type ItemCatalog,
  type ItemCategory,
  type ItemDefinition,
} from "./catalog.js"
export {
  CORA_INVENTORY_EQUIP,
  CORA_INVENTORY_GET,
  CORA_INVENTORY_GIVE,
  CORA_INVENTORY_GIVE_PERMISSION,
  CORA_INVENTORY_MOVE,
  CORA_INVENTORY_REMOVE,
  CORA_INVENTORY_SPLIT,
  CORA_INVENTORY_UI_REFRESH,
  type EquipItemInput,
  type EquipItemResult,
  equipItemInputSchema,
  type GetInventoryInput,
  type GetInventoryResult,
  type GiveItemInput,
  type GiveItemResult,
  getInventoryInputSchema,
  giveItemInputSchema,
  type InventoryError,
  type InventoryErrorResult,
  type InventorySlot,
  type InventoryUiRefreshPayload,
  type MoveItemInput,
  type MoveItemResult,
  moveItemInputSchema,
  type RemoveItemInput,
  type RemoveItemResult,
  removeItemInputSchema,
  type SplitStackInput,
  type SplitStackResult,
  splitStackInputSchema,
} from "./contract.js"
export {
  type InventorySlotsTable,
  inventoryMigrations,
} from "./migrations.js"
export {
  createInventoryHandlers,
  createInventoryModule,
  DEFAULT_INVENTORY_MAX_WEIGHT,
  DEFAULT_INVENTORY_SLOTS,
  type InventoryModuleOptions,
} from "./server/inventory-module.js"
